### Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name":"test",
    "email":"test@example.com",
    "password":"test"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"test@example.com",
    "password":"test"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNTk0MjU5NDY1MTA3fQ.txL9BBf7TGvbws26MonxpRkEKTAlyRNWjIH4GtAvQm0

###############################
### Surveys
###############################
### Get All Survey
GET http://localhost:8000/api/survey
Authorization: : Bearer {{token}}

### Get Single Survey
GET http://localhost:8000/api/survey/5f03b4af002fc9a100b49254
Authorization: : Bearer {{token}}

### Create
POST http://localhost:8000/api/survey
Authorization: : Bearer {{token}}
Content-Type: application/json

{
    "name":"Survey 1",
    "description":"something survey 1"
}

### Update
PUT http://localhost:8000/api/survey/5f03331200a680e300d6bff8
Authorization: : Bearer {{token}}
Content-Type: application/json

{
    "name":"Survey 1 Update",
    "description":"something survey 1 - Update "
}

### Delete 
DELETE http://localhost:8000/api/survey/5f03331200a680e300d6bff8
Authorization: : Bearer {{token}}

###############################
### Questions
###############################

### Get
GET http://localhost:8000/api/survey/5f03b4af002fc9a100b49254/questions
Authorization: : Bearer {{token}}

### Get Single Question
GET http://localhost:8000/api/question/5f05168b0063d87100d651ff
Authorization: : Bearer {{token}}

### Create
POST http://localhost:8000/api/question/5f03b4af002fc9a100b49254
Authorization: : Bearer {{token}}
Content-Type: application/json

{
    "text":"Question 3?",
    "type":"text",
    "required" : true,
    "data" : {
        "multiple" : true,
        "answers": [
            "I like it very much",
            "I like it",
            "I don't like it",
            "I hate it"
        ]
    }
}

### Update
PUT http://localhost:8000/api/question/5f04bcf000b8e5c900f9465f
Authorization: : Bearer {{token}}
Content-Type: application/json

{
    "text":"Question 2?",
    "type":"choice",
    "required" : true,
    "data" : {
        "multiple" : true,
        "answers": [
            "I like it very much",
            "I like it",
            "I don't like it",
            "I hate it"
        ]
    }
}

### Delete
DELETE http://localhost:8000/api/question/5f04bcf000b8e5c900f9465f
Authorization: : Bearer {{token}}

